version: '3'

services:

  php:
    container_name: php
    build: ./docker/php
    links:
      - postgres
    volumes:
      - .:/var/www/html:cached
    working_dir: /var/www/html
    environment:
      XDEBUG_CONFIG: "remote_host=docker.for.win.localhost idekey=IDE_XDEBUG"

  nginx:
    container_name: nginx
    image: nginx:stable
    ports:
      - 85:80 
    links:
      - php
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./docker/pgdata:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: say_it
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    container_name: elasticsearch
    ports:
      - 9200:9200